# Generated by Django 5.2.6 on 2025-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_producto_imagen_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Comedor', 'Comedor'), ('Sillones y Sillas', 'Sillones y Sillas'), ('Decoración de Interior', 'Decoración de Interior'), ('Baño', 'Baño'), ('Iluminación', 'Iluminación'), ('Cortinas', 'Cortinas'), ('Otros', 'Otros')], max_length=50),
        ),
    ]
