# Generated by Django 5.2.6 on 2025-10-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_perfil_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='comentario',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
